
## Disclaimer {.unnumbered}

After a friend helped me install Slackware on my first computer, the first software I  used was \LaTeX. I have loved it ever since, even though our relationship has sometimes been complicated. Over the years, I have used it for many things, from drawing circuits and graphs, to making presentations to writing love letters—no kidding. I have also written many tools that use and generate \LaTeX. However, I think I spent way too much time getting things "perfect"; fine-tuning diagrams, getting the right alignment, and so on. In that regard, I'm glad to be living in the age of LLMs. I wish I had had one years ago.  

All this long prolegomenon to say that I used an LLM here and there to write the code that generates some of the figures in this book. For me, it was clear from the beginning that the figures had to be generated programmatically. I reused a few libraries and I had written in the past, but using the LLM allowed me to move fast and focus elsewhere.  I made that code open source in the hope that it might be useful to someone else. I tried to sanitize it and maintain a coherent structure, but it is still LLM code.

That code is a dependency of this book and can be found at [yoyo-plots](https://github.com/twaclaw/yoyo-plots)^[https://github.com/twaclaw/yoyo-plots].
