## Comparing fractions

The reason the integers [$\color{blue}{\mathbb{Z}}$]{.scale factor="2"} are included in the rational numbers [$\color{purple}{\mathbb{Q}}$]{.scale factor="2"} is that the integers can be represented as fractions.


For example, no matter how many slices a pizza is divided into, if you eat all of them, you have eaten $1$ whole pizza.


```{python}
#| echo: false
#| fig-align: "center"

import importlib
import yoyo_plots.division
import fractions
from attr import s
importlib.reload(yoyo_plots.division)

from yoyo_plots.division import Pizza
from yoyo_plots.common import combine_svgs, display_vector

pizzas = [Pizza(numerator=i, denominator=j, flavour="bianca", division_color="lightgray", draw_fraction=True) for i, j in [(2, 2), (5, 5), (7, 7)]]


display_vector(combine_svgs(pizzas, separators="="))
```

The same applies to any other integer. For example, $2$ can be written as:

:::{.big-math}
$$
2 = \frac{2}{1} =  \frac{4}{2} = \frac{6}{3} = \frac{8}{4} = \cdots
$$
:::

A fraction is equal to an integer whenever the denominator exactly divides the numerator. Here is another example:

:::{.big-math}
$$
-3 = \frac{-3}{1} =  \frac{-6}{2} = \frac{-9}{3} = \frac{-12}{4} = \cdots
$$
:::

Convince yourself that when the numerator and the denominator are equal, the fraction is equal to $1$. If the absolute value of the numerator is greater than the absolute value of the denominator, the absolute value of  fraction is greater than $1$. Finally, if the absolute value of the numerator is less than the absolute value of the denominator, the absolute value of the fraction is less than $1$.


:::{.fun-fact title="Absolute value"}
The absolute value of a number is the number's value without sign. For example, the absolute value of $-3$, represented as $|-3|$, is $3$, and the absolute value of $3$, represented as $|3|$, is also $3$.
:::

:::{.big-math}
$$
\frac{a}{a} = 1 \quad \text{for any } a \neq 0
$$
$$
|\frac{a}{b}| > 1 \quad \text{if } |a| > |b| \quad \text{and } b \neq 0
$$

$$
|\frac{a}{b}| < 1 \quad \text{if } |a| < |b| \quad \text{and } b \neq 0
$$
:::

### Exercises {.unnumbered .unlisted}

Write down the following fractions and determine whether they are equal to, greater than, or less than $1$:


```{python}
#| echo: false
#| fig-align: "center"

import importlib
import yoyo_plots.division
from attr import s
importlib.reload(yoyo_plots.division)

from yoyo_plots.division import Pizza
from yoyo_plots.common import combine_svgs, display_vector

fractions = [(1, 2), (2, 3), (5, 5), (10, 3), (7, 5), (6, 6), (20, 8)]

for enumerator, denominator in fractions:
    if enumerator > denominator:
        npizze = enumerator // denominator
        remainder = enumerator % denominator
        pizze = [Pizza(numerator=denominator, denominator=denominator, flavour="margherita", division_color="lightgray", draw_fraction=False) for _ in range(npizze)] + [Pizza(numerator=remainder, denominator=denominator, flavour="margherita", division_color="lightgray", draw_fraction=True, font_color="white")]
        display_vector(combine_svgs(pizze))
    else:
        pizza = Pizza(numerator=enumerator, denominator=denominator, flavour="margherita", division_color="lightgray", draw_fraction=True, font_color="white") 
        display_vector(pizza)

```


Compare the following quantities and write the appropriate symbol in the empty box: either $<$, or $>$, or $=$.


```{python}
#| echo: false
#| fig-align: "center"

import importlib
import yoyo_plots.division
from attr import s
importlib.reload(yoyo_plots.division)

from yoyo_plots.division import Pizza
from yoyo_plots.common import combine_svgs, display_vector

pairs = [((1, 3), (2, 3)), ((3, 4), (1, 4)), ((6, 7), (2, 7)), ((5,5), (4, 5)), ((2,2), (3,3)), ((2, 4),(1, 2)), ((1,2), (1,3)), ((1,2), (2, 3))]

for p in pairs:
    pizza1 = Pizza(numerator=p[0][0], denominator=p[0][1], flavour="margherita", division_color="lightgray", draw_fraction=True, font_color="black") 
    pizza2 = Pizza(numerator=p[1][0], denominator=p[1][1], flavour="margherita", division_color="lightgray", draw_fraction=True, font_color="black") 
    display_vector(combine_svgs([pizza1, pizza2], separators=[{"type": "box", "width": 80,  "height": 80}]))
```
