## Additional thoughts on addition

Pun intended $\text{[wink:1.5em]{.twemoji}}$.



### Generating the natural numbers {.unlisted .unnumbered}

In a way, counting and adding up are the same thing. Each of the counting numbers can be obtained by adding $\color{blue}{1}$ to the $\color{red}{\text{previous}}$ one.

```{.tikz fig-align="center"}
\begin{tikzpicture}[>=stealth, x=1.5cm, every node/.style={font=\Large}]
  % Define the numbers
  \node (n0) at (0,0) {$0$};
  \node (n1) at (1,0) {$1$};
  \node (n2) at (2,0) {$2$};
  \node (n3) at (3,0) {$3$};
  \node (n4) at (4,0) {$4$};
  \node (ndots) at (5,0) {$\dots$};
  \node (nm1) at (6,0) {$n-1$};
  \node (nn) at (7,0) {$n$};
  
  % Draw the curved arrows with +1
  \foreach \i/\j in {n0/n1, n1/n2, n2/n3, n3/n4, n4/ndots, ndots/nm1, nm1/nn} {
    \draw[->, blue, thick] (\i) to[out=60,in=120] node[above, text=blue] {\footnotesize $+1$} (\j);
  }
\end{tikzpicture}
```

That means that if we start with $0$, the next number is ${\color{red}{0}} + \color{blue}{1}$, the next one is ${\color{red}{1}} + \color{blue}{1}$,  and so on.


```{.tikz fig-align="center"}
\begin{tikzpicture}[>=stealth]
  \matrix (m) [matrix of math nodes, nodes={font=\Large}, row sep=0.5em, column sep=0.15em] {
      0 &   &                 &   &               \\
      1 & = & \color{red}{0} & + & \color{blue}{1} \\
      2 & = & \color{red}{1} & + & \color{blue}{1} \\
      3 & = & \color{red}{2} & + & \color{blue}{1} \\
      4 & = & \color{red}{3} & + & \color{blue}{1} \\
      \vdots & & \vdots       &   & \vdots         \\
      n & = & \color{red}{n-1} & + & \color{blue}{1} \\
  };
  \draw[->, gray, shorten >= 2pt, shorten <= 2pt] (m-1-1) -- (m-2-3);
  \draw[->, gray, shorten >= 2pt, shorten <= 2pt] (m-2-1) -- (m-3-3);
  \draw[->, gray, shorten >= 2pt, shorten <= 2pt] (m-3-1) -- (m-4-3);
  \draw[->, gray, shorten >= 2pt, shorten <= 2pt] (m-4-1) -- (m-5-3);
\end{tikzpicture}
```

We can say that the counting numbers are **generated by** $\color{blue}{1}$. In other words, there is a **successor** _function_ $\text{succ}:\mathbb{N} \to \mathbb{N}$ that takes a natural number and gives you the next one.  


:::{.big-math}
$$
\text{succ}(n) = n + \color{blue}{1}
$$
:::


We will learn more about functions later on. For now, think of functions as magic boxes that take something and give something back. In this case, the magic box takes a number and returns the next one.


:::{.big-math}
$$
n \to \text{[top_hat:1.0em]{.twemoji}} \to n + \color{blue}{1}
$$
:::


### The lazy algorist {.unnumbered .unlisted}

Imagine I ask you to find the sum of the numbers you have learned so far, that is from $0$ to $9$.  Instead of writing the explicit sum $0 + 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9$, you can write it more succinctly as:




:::{.content-visible when-format="html"}
:::{.big-math}
$$
\sum_{i=0}^9 i
$$
:::
:::



:::{.content-visible when-format="pdf"}
:::{.big-math}
:::{{latex}}
\begin{equation*}
    \sum_{\eqnmarkbox[OliveGreen]{i}{i}=\eqnmarkbox[blue]{from}{0}}^{\eqnmarkbox[blue]{to}{9}} {\eqnmarkbox[red]{ki}{i}}
\annotate[yshift=1em]{above,right}{ki}{Expression depending on $i$}
\annotate[yshift=-0.2em]{below,right}{from}{from}
\annotate[yshift=0.2em]{above,left}{to}{to}
\annotate[yshift=-0.2em]{below,left}{i}{summation variable}
\end{equation*}
\vspace{1em}
:::
:::
:::



Which is read "the sum of $i$ from $0$ to $9$". The symbol $\sum$ is the Greek letter sigma.

:::{.big-math size="20pt"}
$$
\sum_{i=0}^{9} i = 0 + 1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9
$$
:::


Admitedly, 10 numbers is not that much, but later, when we learn bigger and bigger numbers, this notation will come handy.


Mathemathicians and programmers are lazy. They don't like to write the same thing over and over again. Instead, they *loop* their way out.

We can also write a program, for instance in Python, to do the same thing:

```{python}
def sum(start, end):
    total = 0
    for i in range(start, end+1):
        total += i
    return total
```

This algorithm has linear time complexity because we have to loop through all the numbers from 0, to 9. People who study algorithms say that this algorithm is $\mathcal{O}(n)$ which is thought to be good. For this particular example, there is a shortcut that will allow us to compute the sum in constant time $\mathcal{O}(1)$. We will come back to this later on.


