## Kangaroo math $\text{[kangaroo:1em]{.twemoji}}$


::: {.story-time title="The Gigantic Turnip" image="/static_images/turnip.pdf" scale="1.1" width="0.7" ref="Read more about this and other cumulative tales at https://wikipedia.org/"}

"The Gigantic Turnip" is a cumulative or _chain_ folk tale. 
In a cumulative tale, the action repeats and builds in a cumulative manner. 

The story is about an old man and an old woman who lived in a crooked cottage and owned the following animals:


- $\text{[cow:1.5em:-0.3em:1]{.twemoji}}$
- $\text{[pig:1.5em:-0.3em:2]{.twemoji}}$
- $\text{[black_cat:1.5em:-0.3em:3]{.twemoji}}$
- $\text{[rooster:1.5em:-0.3em:4]{.twemoji}}$
- $\text{[swan:1.5em:-0.3em:5]{.twemoji}}$
- $\text{[baby_chick:1.5em:-0.3em:6]{.twemoji}}$
:::

The numbers representing the number of each of these animals form an arithmetic progression, or arithmetic sequence, because the difference between any two consecutive numbers is constant. In this case, the common difference is $1$.

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range

fig = draw_handwritten_range(list(range(1, 7)), font_size=30, rows=1, font_color="fuchsia", append_comma=True)
display_vector(fig)
```

In fact, the natural numbers [$\color{red}{\mathbb{N}}$]{.scale factor="2"}  are an arithmetic progression as well. As we saw before, the natural numbers can be generated by starting from $0$ and repeatedly adding $1$. 



```{python}
#| echo: false 
#| fig-align: "center"

from yoyo_plots.number_line import NumberLine
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f998_kangaroo_flipped.svg"
freq = 1
arc = {"color": "fuchsia", "len": freq, "text": f"+{freq}"}
fig = (NumberLine(0, 6, tick_frequency=1)
 .add_tick_icons({0: image})
 .add_arcs({"all": arc})
)
display_vector(fig)

```

Our kangaroo $\text{[kangaroo:2em]{.twemoji}}$ generates the natural numbers by jumping by ones.

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range

fig = draw_handwritten_range(list(range(13)), font_size=30, font_color="fuchsia", append_comma=True, add_ellipsis=True, rows=2)
display_vector(fig)
```


There are two things you should know about our kangaroo $\text{[kangaroo:2em]{.twemoji}}$. First, his name is Joey, and he can jump more than one unit at a time. For example, he can jump two units at a time.


```{python}
#| echo: false 
#| fig-align: "center"

from yoyo_plots.number_line import NumberLine
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f998_kangaroo_flipped.svg"
freq = 2
arc = {"color": "fuchsia", "len": freq, "text": f"+{freq}"}
fig = (NumberLine(0, 10, tick_frequency=1)
 .add_tick_icons({0: image})
 .add_arcs({i: arc for i in range(0, 11, freq)})
)
display_vector(fig)

```

If we follow Joey, we get the sequence:

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range

fig = draw_handwritten_range(list(range(0, 20, 2)), font_size=30, rows=1, font_color="fuchsia", append_comma=True, add_ellipsis=True)
display_vector(fig)
```


Joey can, of course,  also jump in threes.

```{python}
#| echo: false 
#| fig-align: "center"

from yoyo_plots.number_line import NumberLine
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f998_kangaroo_flipped.svg"
freq = 3
arc = {"color": "fuchsia", "len": freq, "text": f"+{freq}"}
fig = (NumberLine(0, 12, tick_frequency=1)
 .add_tick_icons({0: image})
 .add_arcs({i: arc for i in range(0, 13, freq)})
)
display_vector(fig)
```

On the number line, we can skip the numbers that aren't part of Joey's jumps. The sequence remains the same; we are simply changing how we visualize it.


```{python}
#| echo: false 
#| fig-align: "center"

from yoyo_plots.number_line import NumberLine
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f998_kangaroo_flipped.svg"
freq = 3
arc = {"color": "fuchsia", "len": freq, "text": f"+{freq}"}
fig = (NumberLine(0, 18, tick_frequency=3)
 .add_tick_icons({0: image})
 .add_arcs({i: arc for i in range(0, 18, freq)})
)
display_vector(fig)
```

In both cases, the resulting sequence is the same:


```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range

fig = draw_handwritten_range(list(range(0, 27, 3)), font_size=30, rows=1, font_color="fuchsia", append_comma=True, add_ellipsis=True)
display_vector(fig)
```

### Why is Kangaroo math important? {.unnumbered .unlisted}

There are two important reasons to learn Kangaroo Math. First, it allows you to count faster.  Second, it provides a solid foundation for learning multiplication, division, and exponentiation, as we will see in the next sections.

Counting by jumping two, three, or five units at a time allows you to count faster, just as climbing a staircase becomes quicker when you skip steps.

For example, you can climb a staircase twice as fast if you jump two steps at a time instead of one step at a time.


```{python}
#| echo: false
#| fig-align: "center"
from yoyo_plots.staircase import draw_staircase
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f3c3-1f3ff_running_person.svg"
arc = {"color": "lightblue", "len": 2, "text": "+2"}
n = 6
fig = draw_staircase(
    nsteps=n,
    arcs={i: arc for i in range(0, n, 2)},
    icons={i: image for i in range(0, n, 2)},
    icon_size=2.0,
)
display_vector(fig)
```


:::{.fun-fact title="Kangaroo math and multiplication" image="/static_images/kangaroo_roadsign.pdf" width="0.6" scale="1.0"}
Multiplication is simply a shortcut for counting faster.
We will learn later that there are even faster counting tricks.
:::

### Exercises {.unnumbered .unlisted}

Let's practice our Kangaroo Math! Write down the sequences generated when Joey jumps $n$ units at a time. 



```{python}
#| echo: false 
#| fig-align: "left"

from yoyo_plots.number_line import NumberLine
from yoyo_plots.common import display_vector
from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range


image = "/static_images/emojis/1f998_kangaroo_flipped.svg"

for freq in [5, 2, 3, 4,  6, 10]:
    arc = {"color": "fuchsia", "len": freq, "text": f"+{freq}"}
    fig = (NumberLine(0, 6*freq+1, tick_frequency=freq)
     .add_tick_icons({0: image}, tick_icon_size=0.8)
     .add_arcs({i: arc for i in range(0, 6*freq+1, freq)})
    )
    display_vector(fig)

    if freq == 5:
        fig = draw_handwritten_range(list(range(0, freq*20, freq)), font_size=30, rows=3, font_color="fuchsia", append_comma=True, add_ellipsis=True)
    else:
        fig = draw_handwritten_range(list(range(0, freq*3, freq)), font_size=30, rows=1, font_color="fuchsia", append_comma=True, add_ellipsis=False)
    display_vector(fig)

    for _ in range(5):
        # add white space
        print()
```


Based on the following image, answer the following questions:

```{python}
#| echo: false
#| fig-align: "center"
from yoyo_plots.staircase import draw_staircase
from yoyo_plots.common import display_vector

image = "/static_images/emojis/1f938-1f3ff_person_upsidedown.svg"
arc = {"color": "lightblue", "len": 2, "text": "+2"}
n = 12
fig = draw_staircase(
    nsteps=n,
    icons={0: image},
    icon_size=2.0,
)
display_vector(fig)
```

- When you climb the stairs one step at a time, it takes you $12$ seconds to reach the top. If you jump $3$ steps at a time at the same speed, how long would it take you to get to the top? 
- If you want to climb the stairs in $2$ seconds, how many steps would you have to jump at a time?

