## How could we represent numbers greater than 9?

If we only have ten *digits* or symbols:

```{python}
# | echo: false
# | fig-cap: "The decimal numbers. Ten digits."

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range

fig = draw_handwritten_range(list(range(10)), font_size=50, rows=1, font_color="fuchsia", append_comma=True)
display_vector(fig)
```

:::{.fun-fact title="Decem digiti" image="/static_images/fingers.pdf" width="0.6" scale="1.0"}
The word "digit" comes from the Latin word "digitus," meaning "finger." The plural form is "digiti."
:::

:::{.question}
How to possibly represent numbers above 9? Any ideas?
:::

If  we don't want to introduce new symbols, it seems the only option is  to reuse the same symbols in some way $\text{[thinking:1.5em]{.twemoji}}$. We need to exploit a different property or attribute of these digits somehow. Any ideas?

What about their color? We could establish a color convention where the value of the digitgs  depends on their color.

\scalebox{3}{$\color{red}{9}$, $\color{blue}{9}$, $\color{black}{9}$, $\color{green}{9}$}

Instead of color, we could use another attribute, such as size.

$9$, \scalebox{2}{$9$}, \scalebox{3}{$9$}, \scalebox{5}{$9$}

If you quickly scan the page numbers in this book, you will see that this is not how it is done. Instead, we use the **position** of the digits. 

Just as we can use the letters of the alphabet to write an infinite number of sentences and books, we can also use the ten decimal digits to represent infinite many numbers.


## Positional number system

Numbers greater than $9$ can be represented by combinations of the same ten digits in different positions. Any combination that starts with a number other than $0$ is a valid number. Let's see some examples:

:::{.big-math size="25"}
$$
10, \quad 123, \quad 9999999, \quad 100000000000, \quad \ldots
$$
:::

:::{.fun-fact title="Positional number system in a nutshell"}
The defining feature of the positional number system is that the value of a digit depends on its position in the number.
For instance, in the number $333$, each digit $3$ has a different value.  

:::{.content-visible when-format="html"}
```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.hotel import Label, Number


label = Label(values=[Number(3, "black")]*3, draw_grid=False)

display_vector(label)
```
:::

:::{.content-visible when-format="pdf"}
:::{.big-math size="20"}
:::{{latex}}
\begin{equation*}
\eqnmark[Blue]{k1}{3}\eqnmark[Red]{k2}{3}\eqnmark[Black]{k3}{3}
\annotate[yshift=0.5em]{above,left}{k1}{Greatest value}
\annotate[yshift=0.5em]{above,right}{k2}{Second greatest value}
\annotate[yshift=-0.5em]{below,right}{k3}{Lowest value}
\end{equation*}
:::
:::
:::

The farther to the left $\Leftarrow$ a digit is, the larger its value. We will use boxes to  emphasize the positions.

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector
from yoyo_plots.hotel import Label, Number

colors = ["blue", "red", "black"]

label = Label(values=[Number(3, colors[i]) for i in range(3)], draw_grid=True)

display_vector(label)
```
:::

A digit's value changes as soon as it is moved to a different position. For example, the resulting number changes each time the digit $3$ is moved to the left; the larger the position to the left, the larger the number.

```{python}
# | echo: false
# | fig-align: "center"
# | fig-cap: "A digit's value depends on its position. It increases as we move to the left $\\leftarrow$."

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number

colors = ["green", "blue", "red", "black"]

labels = [Label(values=[None]*i + [Number(3, colors[i])] + [None]*(3-i)) for i in range(4)][::-1]

display_vector(combine_svgs(labels, spacing=10, direction="vertical" ))
```

However, in the last example, these are not valid numbers. We need to fill the empty positions to the right.

<!-- - $\text{[woman_police_officer:1.5em:-0.3em]{.twemoji}}$ Any positions to the right of a digit must be filled with additional digits. For the time being, let's use zeros, but any digits will do.   -->


```{python}
# | echo: false
# | fig-align: "center"
# | fig-cap: "The digit 3 has different values depending on its position."

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number

colors = ["green", "blue", "red", "black"]

labels = [Label(values=[None]*i + [Number(3, colors[i])] + [Number(0, "black")]*(3-i)) for i in range(4)]

display_vector(combine_svgs(labels, spacing=50, direction="horizontal" ))
```

You don't need to know what the numbers are; you only need to know that the further to the left the digit $3$ is, the larger the value it represents^[We don't need to draw the boxes. What matters is the position of each digit.]:

:::{.content-visible when-format="html"}
:::{.big-math}
$$
{\color{olive}{3}}000 > {\color{blue}{3}}00 > {\color{red}{3}}0 > 3
$$
:::
:::

:::{.content-visible when-format="pdf"}
:::{.big-math}
:::{{latex}}
\begin{equation*}
\eqnmarkbox[OliveGreen]{thousands}{3}000 > \eqnmarkbox[Blue]{hundreds}{3}00 > \eqnmarkbox[Red]{tens}{3}0 > \eqnmarkbox[Black]{ones}{3}
\annotate[yshift=1em]{above,left}{thousands}{Thousands}
\annotate[yshift=1em]{above,left}{hundreds}{Hundreds}
\annotate[yshift=1em]{above,left}{tens}{Tens}
\annotate[yshift=1em]{above,left}{ones}{Ones: units}
\end{equation*}
:::
:::
:::



Even if you don't know what the numbers mean, you can use what you just learned to determine which number is larger and who is faster in the figure below. 

:::{question}
Explain why?
:::

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.speed import speed_limit

s1 = speed_limit(1, "km/h", image_path="/static_images/emojis/1f994_hedgehog.svg")
s2 = speed_limit(10, "km/h", image_path="/static_images/emojis/1f3c3-200d-2640-fe0f-jogging-woman.svg")
s3 = speed_limit(100, "km/h", image_path="/static_images/emojis/1f406_leopard.svg")

combined = combine_svgs([s1, s2, s3], direction="horizontal")
display_vector(combined)
```




<!-- Let's quickly recap what we just learned. The following are some rules $\text{[woman_police_officer:1.5em]{.twemoji}}$ of the positional number system:

- $\text{[woman_police_officer:1.5em:-0.3em]{.twemoji}}$ The first position is the one on the far right. Values increase as we move to the left. 

- $\text{[woman_police_officer:1.5em:-0.3em]{.twemoji}}$ Any positions to the left of the number that are not used are left empty^[They can also be filled with zeros.]. 

- $\text{[woman_police_officer:1.5em:-0.3em]{.twemoji}}$ The same digit can represent different values depending on where it is in a number. The further to the left the digit is, the larger the value it represents. 

- $\text{[woman_police_officer:1.5em:-0.3em]{.twemoji}}$ Any positions to the right of a digit must be filled with additional digits. -->

<!-- Okay, I understand that we need more positions that will contain digits. But how will those digits be selected to construct and represent larger numbers?  -->


### How to count and construct numbers beyond $9$? {.unnumbered .unlisted}

We now how to count until $9$:
```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number


labels = [Label(values=[Number(i, "black")], draw_grid=True) for i in range(10)]

display_vector(combine_svgs(labels, spacing=10, direction="horizontal", separators="-", separator_font_size=40))
```

To count beyond $9$ we need two things: more positions and reusing the same digits.

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number


r1_labels = [Label(values=[None, Number(i, "black")], draw_grid=True) for i in range(10)]
r2_labels = [Label(values=[Number(1, "red"), Number(i, "black")], draw_grid=True) for i in range(10)]

r1 = combine_svgs(r1_labels, spacing=10, direction="horizontal")
r2 = combine_svgs(r2_labels, spacing=10, direction="horizontal")

c = combine_svgs([r1, r2], spacing=10, direction="vertical")
display_vector(c)
```

Notice that after $9$ we start reusing the same digits, beginning with $0$, but now they are prefixed by the digit $\color{red}{1}$.

:::{.question}
Can you guess what number comes after $19$? 
:::

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number

n = 5
rows = [combine_svgs([Label(values=[Number(j, "red"), Number(i, "black")], draw_grid=True) for i in range(10)], spacing=10, direction="horizontal") for j in range(n)]

c = combine_svgs(rows, spacing=10, direction="vertical")
display_vector(c)
```

As you probably guessed, after $19$ comes $20$. Each time we reach a number ending in $9$, we increase the leftmost digit by $1$. If you only look at the $\color{red}{\text{red}}$ digits, you will see that we are also counting in that position: $\color{red}{0, 1, 2, 3, 4, \cdots}$. Here, we prefixed the first ten numbers with $\color{red}{0}$ to emphasize that, but that doesn't change the values.

:::{.question}
How high do you think we can count with two positions?
:::

If you answered $99$, you are correct!


```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number

rows = [combine_svgs([Label(values=[Number(j, "red"), Number(i, "black")], draw_grid=True) for i in range(10)], spacing=10, direction="horizontal") for j in range(8,10)]

c = combine_svgs(rows, spacing=10, direction="vertical")
display_vector(c)
```

:::{.question title="And now what?"}
How to continue after $99$?
:::

The answer is always the same: we need two things —more positions and reusing the same digits.

```{python}
# | echo: false
# | fig-align: "center"

from yoyo_plots.common import display_vector, combine_svgs
from yoyo_plots.hotel import Label, Number

rows = [combine_svgs([Label(values=[Number(0 if j < 2 else 1, "blue"), Number(((j + 8) % 10), "red"), Number(i, "black")], draw_grid=True) for i in range(10)], spacing=10, direction="horizontal") for j in range(4)]

c = combine_svgs(rows, spacing=10, direction="vertical")
display_vector(c)
```

Notice that with the $\color{blue}{\text{blue}}$ digits, we are also counting in the third position: $\color{blue}{0, 1, 2, 3, 4, \cdots}$. Only, we count slower than we did with the $\color{red}{\text{red}}$ digits. The most to the left we go, the slower we count.


This is a recurring process. We continue to do the same thing: add positions and reuse the same digits to create larger and larger numbers.

### Exercises {.unnumbered .unlisted}

- Write the numbers from $0$ to $31$.

```{python}
#| echo: false 
#| fig-align: "left"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range


fig = draw_handwritten_range(list(range(4)), font_size=40, rows=1, font_color="lightgray", append_comma=True, add_ellipsis=False)
display_vector(fig)

for _ in range(10):
    print()
```

- Write the numbers from $90$ to $110$.

```{python}
#| echo: false 
#| fig-align: "left"

from yoyo_plots.common import display_vector
from yoyo_plots.quantities import draw_handwritten_range


fig = draw_handwritten_range(list(range(90, 95)), font_size=40, rows=1, font_color="lightgray", append_comma=True, add_ellipsis=False)
display_vector(fig)

for _ in range(5):
    print()
```








In order to master these insights and the way numbers are constructed, we are going on vacation! We'll be staying at the Numbers Grand Hotel.
